name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: LuccaMenegatti
          template: classic     
          base: header
          config_timezone: America/Sao_Paulo
          
          config_style: |
             background-color: #0d1117;
             color: #c9d1d9;
             h1, h2, h3 { color: #41A8BF; }
             .stat { color: #c9d1d9; }
             
             /* TRUQUE: Esconde a foto grande e o nome, deixando só os números */
             .header .avatar { display: none !important; }
             .header h1 { display: none !important; } /* Nome */
             .header h2 { display: none !important; } /* Data de entrada */
             .header { padding-bottom: 20px; } /* Ajusta espaçamento */

          # --- Plugin: Linguagens ---
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_details: bytes-size, percentage
          
          # --- Plugin: Calendário (Streak) ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
