name: Metrics
on:
  # Atualiza as 00:00 todos os dias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente na aba Actions
  workflow_dispatch:
  # Roda a cada push na branch main
  push: {branches: ["main", "master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # --- Configurações Principais ---
          user: LuccaMenegatti
          template: classic
          base: repositories
          config_timezone: America/Sao_Paulo
          
          config_style: |
             background-color: #0d1117;
             color: #c9d1d9;
             h1, h2, h3 { color: #41A8BF; }
             .stat { color: #c9d1d9; }

          # --- Plugin: Linguagens ---
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_details: bytes-size, percentage
          
          # --- Plugin: Calendário (Streak) ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year # Mostra 6 meses (fica menor que o anual)
